### ISSUE TITLE
include ClucHAnix_hhll too

### ISSUE THREAD

**Issue by JhorAVi** [thinkong/freqtradestrategies#2]
ClucHAnix_hhll is a very good performer in my simple tests. 
I love your project. I'll keep on following this. thanks

**Comment by thinkong** [comment]
> ClucHAnix_hhll is a very good performer in my simple tests. I love your project. I'll keep on following this. thanks

I have added the strategy. Let's wait and see :)

**Comment by thinkong** [comment]
The result wasn't as expected. Maybe I missed something out.

**Comment by JhorAVi** [comment]
I'm looking on your 5m results and ClucHAnix_hhll seems to be ahead of the pack except against Elliot because Elliot is known to be a cheater in backtest :). I may have wrongly interpreted the "profit sum" and "profit total" on the table though because it's displaying very big percentages. Why is that?

**Comment by thinkong** [comment]
Hey thanks for pointing it out. 
I changed some stuff around to match the backtest results when you run backtest.
As for ClucHAnix_hhll it seems to be bad during downtrends making -25% during the downtrend times.

**Comment by JhorAVi** [comment]
Thanks it 's a little clearer now. But the percent symbol seems interchanged

**Comment by thinkong** [comment]
Not quite sure what you mean by interchanged.. They do seem right to me..
